Create searchInArray.c
aryan-0102/Learning_C pull request #3
Opened 2023-10-15 08:15 UTC by TRIPATHISHIWANSHI

2023-10-15 10:15 UTC, aryan-0102 requested changes
Few things to be changed

2023-10-15 10:15 UTC, aryan-0102 commented on Practice Questions/searchInArray.c
> +
The code needs to be updated to handle edge cases, input validation, and array size is fixed, code only finds the first occurrence of item

2023-10-15 10:42 UTC, TRIPATHISHIWANSHI reviewed
I have made changes..please review it

2023-10-16 07:20 UTC, aryan-0102 approved these changes

2023-10-16 07:21 UTC, merged